environment:
  nodejs_version: "8"

platform:
  - x64

install:
  - cmd: git submodule update --init
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set msvs_version 2015 --global
  - npm config set target_arch %PLATFORM% --global
  - npm install -g node-gyp

build_script:
  - npm install --ignore-scripts
  - npm run rebuild

test_script:
  - node --version
  - npm --version
  - npm test

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") {./node_modules/.bin/prebuild --all --strip -u $env:GITHUB_TOKEN}
